import assert from "node:assert/strict";
import { readdir } from "node:fs/promises";
import { describe, it } from "node:test";
import { defaultMigrationsDir, loadMigrations } from "../src/db/migrations.js";

describe("Postgres migrations", () => {
  it("include deterministic queue, event idempotency, decisions, and receipts schema", async () => {
    const migrations = await loadMigrations();
    const sql = migrations.map((migration) => migration.sql).join("\n");
    const expectedMigrationIds = (await readdir(await defaultMigrationsDir()))
      .filter((file) => file.endsWith(".sql"))
      .sort();

    assert.deepEqual(migrations.map((migration) => migration.id), expectedMigrationIds);
    assert.match(sql, /CREATE TABLE IF NOT EXISTS events/);
    assert.match(sql, /UNIQUE \(source, idempotency_key\)/);
    assert.match(sql, /CREATE TABLE IF NOT EXISTS review_packets/);
    assert.match(sql, /CREATE TABLE IF NOT EXISTS queue_items/);
    assert.match(sql, /CHECK \(state IN \('ready', 'leased', 'deferred', 'done', 'dead'\)\)/);
    assert.match(sql, /CREATE TABLE IF NOT EXISTS route_decisions/);
    assert.match(sql, /CREATE TABLE IF NOT EXISTS receipts/);
    assert.match(sql, /CREATE TABLE IF NOT EXISTS context_restore_requests/);
    assert.match(sql, /CHECK \(status IN \('pending', 'leased', 'done'\)\)/);
    assert.match(sql, /CHECK \(status IN \('pending', 'leased', 'done', 'failed'\)\)/);
    assert.match(sql, /context_restore_requests_pending_idx/);
    assert.match(sql, /context_restore_requests_stale_lease_idx/);
    assert.match(sql, /CREATE TABLE IF NOT EXISTS metric_counters/);
    assert.match(sql, /CREATE TABLE IF NOT EXISTS activity_events/);
    assert.match(sql, /activity_events_occurred_at_idx/);
    assert.match(sql, /CREATE TABLE IF NOT EXISTS mcp_poll_states/);
    assert.match(sql, /mcp_poll_states_updated_at_idx/);
    assert.match(sql, /CREATE TABLE IF NOT EXISTS task_messages/);
    assert.match(sql, /idempotency_key text NOT NULL UNIQUE/);
    assert.match(sql, /CHECK \(status IN \('attempted', 'sent', 'blocked', 'failed'\)\)/);
    assert.match(sql, /task_messages_task_session_id_idx/);
    assert.match(sql, /CREATE TABLE IF NOT EXISTS agent_runs/);
    assert.match(sql, /agent_runs_task_status_idx/);
    assert.match(sql, /CREATE TABLE task_workspace_snapshots/);
    assert.match(sql, /task_id text PRIMARY KEY/);
    assert.match(sql, /snapshot jsonb NOT NULL/);
    assert.match(sql, /queue_items_ready_rank_idx/);
    assert.match(sql, /queue_items_stale_lease_idx/);
    assert.match(sql, /CREATE TABLE queue_action_attempts/);
    assert.match(sql, /idempotency_key text PRIMARY KEY/);
    assert.match(sql, /queue_action_attempts_queue_item_id_idx/);
    assert.match(sql, /CREATE TABLE task_session_terminal_refs/);
    assert.match(sql, /task_session_id text PRIMARY KEY/);
    assert.match(sql, /terminal_ref text NOT NULL/);
    assert.match(sql, /CREATE TABLE onboarding_rejections/);
    assert.match(sql, /proposal_key text PRIMARY KEY/);
    assert.match(sql, /CREATE TABLE onboarding_approval_batches/);
    assert.match(sql, /CREATE TABLE tasks/);
    assert.match(sql, /tasks_primary_anchor_uidx/);
    assert.match(sql, /CREATE TABLE task_layouts/);
    assert.match(sql, /CREATE TABLE current_task_state/);
    assert.match(sql, /ALTER TABLE tasks ADD COLUMN aerospace_workspace_id text/);
    assert.match(sql, /tasks_aerospace_workspace_idx/);
    assert.match(sql, /CREATE TABLE paper_triggers/);
    assert.match(sql, /paper_triggers_enabled_event_type_idx/);
    assert.match(sql, /CREATE TABLE paper_trigger_firings/);
    assert.match(sql, /ALTER TABLE window_workspace_observations[\s\S]*ADD COLUMN app_bundle text/);
    assert.match(sql, /ADD COLUMN title_prefix text/);
    assert.match(sql, /window_workspace_observations_slot_idx/);
    assert.match(sql, /ALTER TABLE tasks ADD COLUMN dormant_at timestamptz/);
    assert.match(sql, /tasks_dormant_at_idx/);
    assert.match(sql, /CREATE TABLE follows_window_exclusions/);
    assert.match(sql, /CHECK \(app_bundle IS NOT NULL OR title_substring IS NOT NULL\)/);
    assert.match(sql, /CREATE TABLE IF NOT EXISTS task_window_claims/);
    assert.match(sql, /REFERENCES tasks\(task_id\) ON DELETE CASCADE/);
    assert.match(sql, /idx_task_window_claims_identity/);
    assert.match(sql, /process_root_pid integer/);
    assert.match(sql, /idx_task_window_claims_process_root_pid/);
  });
});
